# ====================================================================
# İŞ AKIŞI 1: VERİ İNDİRME OTOMASYONU (Nihai ve Kararlı Sürüm)
# ====================================================================
name: 1 - Ham Veri İndirme

on:
  schedule:
    # Her gün sabah 07:00'de (UTC) çalışır.
    - cron: '0 7 * * *'
  
  # Manuel çalıştırmayı sağlar
  workflow_dispatch:

jobs:
  download-raw-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Chrome Tarayıcı Kurulumu
        uses: browser-actions/setup-chrome@v1

      - name: ChromeDriver Kurulumu
        id: setup_chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dosyaları İndir (update_list.py)
        id: run_downloader
        env:
          # ChromeDriver kurulum adımının çıktısını CHROME_DRIVER_PATH değişkenine atıyoruz
          CHROME_DRIVER_PATH: ${{ steps.setup_chromedriver.outputs.chromedriver-path }}
        run: python update_list.py

      - name: Ham Veri Değişikliklerini Depoya Gönder
        if: steps.run_downloader.outputs.updated == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ham_veriler/
          git commit -m "Otomatik Ham Veri Güncellemesi: ${{ steps.run_downloader.outputs.summary }}"
          git push --force
